import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { RouterProvider, createRouter } from '@tanstack/react-router';
import "leaflet/dist/leaflet.css";
import './index.css';

// Import the generated route tree (this file will be auto-generated by the Vite plugin)
import { routeTree } from './routeTree.gen';

// 1. Initialize TanStack Query Client
const queryClient = new QueryClient();

// 2. Initialize TanStack Router
const router = createRouter({ routeTree });

// 3. Register the router instance for strict type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>
);
